name: smart_agriculture_app
description: A Flutter Windows desktop app for the Smart Agriculture API.
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: '>=2.19.0 <3.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.6

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
